### ISSUE TITLE
please leverage tag/releases

### ISSUE THREAD

**Issue by drdamour** [cloudpups/authenticated-scripts#1]
i can only adopt a task that has a changelog per policy, i'd probably make use of this if i could sync the rss of github releases to our system

**Comment by JoshuaTheMiller** [comment]
@drdamour sounds good. I'll try and find some time this week to add proper release note creation!

In the meantime, would you care to extrapolate on the changelog requirement of yours?

**Comment by JoshuaTheMiller** [comment]
Here is my first stab at supporting release notes: https://github.com/cloudpups/authenticated-scripts/releases/tag/v0.0.14

(added through a small addition to the pipeline: [addition](https://github.com/cloudpups/authenticated-scripts/blob/main/azure-pipelines.yml#L176-L189))

**Comment by drdamour** [comment]
so now we can start tracking https://github.com/cloudpups/authenticated-scripts/releases.atom for updates

**Comment by JoshuaTheMiller** [comment]
Yes, every production release to the Marketplace will also get a Git tag and GitHub release 🎉

Will that work for you?

**Comment by JoshuaTheMiller** [comment]
Closing as I've been given a "thumbs up" 😁

![image](https://user-images.githubusercontent.com/4266541/132272632-40e31b80-9a35-41a3-91e5-4f24c19ac1ef.png)
