### ISSUE TITLE
"No results found" in Service Connection select input

### ISSUE THREAD

**Issue by cjbadger** [cloudpups/authenticated-scripts#5]
Hi there, 

I've just installed this extension (Azure DevOps Services), and when using both "Authenticated Powershell" and "Authenticated Bash", the Service Connection select input is empty ("No results found"). I've tried refreshing the input, and can confirm that other tasks in the job are able to access the list of Service Connections from their equivalent menus. Am I doing something wrong here?
![image](https://user-images.githubusercontent.com/94421801/161917493-e834a29c-8e26-484f-9543-594f97b0f76c.png)

Thanks!

Chris.

**Comment by cjbadger** [comment]
Actually, I imagine this is because the service connections I am expecting to see there are Power Platform service connections (that utilize 'service principal/client secret' authentication), whereas this extension expects/supports generic connections (utilizing username/password authentication). Is that right?

**Comment by JoshuaTheMiller** [comment]
Hmm seems I need to reconfigure my notifications 🤔 

> whereas this extension expects/supports generic connections (utilizing username/password authentication)

^ you are correct. I believe this is an opportunity to improve the documentation for this plugin though, so I am going to reopen this issue 🙂

**Comment by luk-rs** [comment]
Any new on this? I've recently installed and am experiencing the same issue

**Comment by JoshuaTheMiller** [comment]
> Any new on this? I've recently installed and am experiencing the same issue

Hey @luk-rs! Long story short, this extension uses the `Generic` service connection type **only**.

![image](https://user-images.githubusercontent.com/4266541/196540278-bccb3484-9f22-46ac-a39c-26d56b0c62e5.png)

**Comment by JoshuaTheMiller** [comment]
Documentation has been updated with the latest deploy to the MS Store 🙂

![image](https://user-images.githubusercontent.com/4266541/196543847-736522f0-0dbd-47c3-a36e-b44030ee85ad.png)

**Comment by luk-rs** [comment]
Hi @JoshuaTheMiller thanks for the info I got it to work using the generic service connections.

**Comment by JoshuaTheMiller** [comment]
> Hi @JoshuaTheMiller thanks for the info I got it to work using the generic service connections.

Good to hear! Please let me know (by opening an Issue, of course) if you run into anything else!
